parameters:
    env(ELASTICSEARCH_HOST): 'http://localhost:9200'

api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Dto'
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Model'


    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']


    collection:
        pagination:
            items_per_page: 7 # Default value
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value