parameters:
    env(ELASTICSEARCH_HOST): '%env(ELASTICSEARCH_HOST)%'

api_platform:
    mapping:
        paths:
#            - '%kernel.project_dir%/src/Dto'
            - '%kernel.project_dir%/src/Entity'
#            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
#            - '%kernel.project_dir%/src/Model'


    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

#    elasticsearch:
#        hosts: ['%env(ELASTICSEARCH_HOST)%']

    collection:
        pagination:
            items_per_page: 10 # Default value
            client_items_per_page: true # Disabled by default.  Idea: double the range, find the start page, get the results and return the slice to the API call
            items_per_page_parameter_name: itemsPerPage # Default value