easy_admin:
    design:
        menu:
            - { label: 'Bard Home', route: 'app_homepage' }
            - { entity: Work }
            - { entity: Chapter }
            - { entity: Paragraph }
            - { entity: Character }
            - { entity: GutenbergBook }
        # ...

    entities:
        # List the entity class name you want to manage
        - App\Entity\Work
        - App\Entity\Chapter
        - App\Entity\Paragraph
        - App\Entity\Character
        - App\Entity\GutenbergBook
