survos_landing_bundle_oauth:
    resource: '@SurvosBaseBundle/Controller/OAuthController.php'
    prefix: /
    type: annotation

app_logo: {path: /logo, controller: 'Survos\BaseBundle\Controller\LandingController::logo'}
app_profile: {path: /profile, controller: 'Survos\BaseBundle\Controller\LandingController::profile'}
profile: {path: /profile, controller: 'Survos\BaseBundle\Controller\LandingController::profile'}
# required if app_profile is used, since you can change the password from the profile
app_change_password: {path: /change-password, controller: 'Survos\BaseBundle\Controller\LandingController::changePassword'}
app_typography: {path: /typography, controller: 'Survos\BaseBundle\Controller\LandingController::typography'}
survos_base_credits: {path: "/credits/{type}", controller: 'Survos\BaseBundle\Controller\LandingController::credits'}
