<?php // generated by @SurvosLanding/MenuBuilder.php.twig

namespace App\Menu;

use Survos\LandingBundle\Menu\LandingMenuBuilder;

class MenuBuilder extends LandingMenuBuilder
{

    public function createMainMenu(array $options)
    {
        $menu = $this->factory->createItem('root');

$menu->setChildrenAttribute('class', 'nav navbar-nav mr-auto');




try {
} catch (\Exception $e) {
    // probably not loaded.
}


// $menu->addChild('admin', ['route' => 'easyadmin']);

// ... add more children

return $this->cleanupMenu($menu);
}



}