# we in
App\Entity\Work:
  attributes:
    shortTitle:
      groups: ['read', 'Default']
    longTitle:
      groups: ['read', 'Default']
    title:
      groups: ['read', 'Default']
    chapterCount:
      groups: ['read', 'Default']
    year:
      groups: ['read', 'Default']
    totalWords:
      groups: ['read']
    source:
      groups: ['source']
    fountainUrl:
      groups: ['read', 'Default']
    fullText:
      groups: ['read', 'Default']
    GenreType:
      groups: ['read', 'Default']


App\Dto\WorkOutput:
  attributes:
    id:
      groups: ['read', 'Default']
    title:
      groups: ['read', 'write', 'Default']
    longTitle:
      groups: ['read', 'write', 'Default']
    year:
      groups: ['read', 'Default', 'write']
    totalWords:
      groups: ['read', 'Default']
    full_text:
      groups: ['full_text']
