#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# app/config/routes.yaml
admin_user_:
  resource: "@UmbrellaAdminBundle/config/routes/user.yaml"
  prefix: /admin

admin_userprofile_:
  resource: "@UmbrellaAdminBundle/config/routes/user_profile.yaml"
  prefix: /admin

