# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
#    env(ELASTICSEARCH_URL): '%env(SEARCHBOX_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $finderWork: '@fos_elastica.finder.work'
            $finderParagraph: '@fos_elastica.finder.paragraph'
            $searchDSN: '%env(ELASTICSEARCH_HOST)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    JoliCode\Elastically\Client:
        arguments:
            $config:
#                host: '%env(ELASTICSEARCH_HOST)%'
                elastically_mappings_directory: '%kernel.project_dir%/config/mappings'
                elastically_index_class_mapping:
                    works: App\Dto\WorkOutput
                    beers: App\Dto\Beer
                    paragraph: App\Entity\Paragraph
                    work: App\Entity\Work
                elastically_serializer: '@serializer'
                elastically_bulk_size: 10
            $logger: '@logger'


    app.top_menu_builder:
        class: App\Menu\TopMenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@event_dispatcher"
        tags:
            - { name: knp_menu.menu_builder, method: createTopMenu, alias: top_menu }

#    api_platform.elasticsearch.match_filter:
#        public: true

# api/config/services.yaml
    # ...
#    'App\DataTransformer\WorkInputDataTransformer': ~
#    'App\DataTransformer\WorkoutputDataTransformer': ~
      # Uncomment only if autoconfiguration is disabled
    #tags: [ 'api_platform.data_transformer' ]

#    app.title.match_filter:
##        parent:    'api_platform.elasticsearch.match_filter'
#        # parent:    'api_platform.doctrine.orm.search_filter'
#        arguments: [ { 'title': ~, 'name': 'title' }]
#        tags:      [ { name: 'api_platform.filter', id: 'app.title.match_filter' } ]
#        public: true
#
#    app.year.term_filter:
#        parent:    'api_platform.elasticsearch.match_filter'
#        arguments: [ ]
#        tags:      [ { name: 'api_platform.filter', id: 'app.year.term_filter' } ]
#        public: true


        # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
