# api/config/api_platform/resources.yaml
App\Dto\WorkOutput:


#App\Entity\Work:
#  shortName: 'Plays'                   # optional
#  description: 'aka Works' # optional
#  attributes:                          # optional
#    pagination_items_per_page: 30   # optional
#    normalization_context:
#      groups: ['Default']
#    denormalization_context:
#      groups: ['Default']
