# api/config/api_platform/resources.yaml
App\Dto\WorkOutput:
  description: 'In ElasticSearch'
  attributes:                          # optional
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
    pagination_items_per_page: 3

    # https://stackoverflow.com/questions/56793777/how-can-i-use-api-platform-filters-in-yaml
    # https://github.com/api-platform/api-platform/issues/638
    # https://github.com/api-platform/core/issues/1755
    # https://api-platform.com/docs/core/filters/#basic-knowledge
    # https://github.com/api-platform/core/blob/df7087816254085741820cd1513aeb5fdaaf13a1/tests/Fixtures/app/config/config_orm.yml#L5
#    collection_operations:
#      get:
#        filters:
#          - 'app.title.match_filter'
#          - 'app.year.term_filter'


  properties:
    id:
      attributes:
        identifier: true
        type: integer

App\Entity\Character:
  shortName: 'Characters'                   # optional
  description: 'The characters acting the play'
  attributes:                          # optional
    pagination_items_per_page: 30   # optional
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']

#  collection_operations:
#    get_abc:
#        method: get
#        filters:
#          - app.character.search_filter

