# api/config/api_platform/resources.yaml
App\Dto\WorkOutput:
  description: 'In ElasticSearch'
  attributes:                          # optional
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
    pagination_items_per_page: 3
    # https://github.com/api-platform/api-platform/issues/638
    # https://api-platform.com/docs/core/filters/#basic-knowledge
    # https://github.com/api-platform/core/blob/df7087816254085741820cd1513aeb5fdaaf13a1/tests/Fixtures/app/config/config_orm.yml#L5
    collection_operations:
      get:
        filters:
          - 'app.title.match_filter'
          - 'app.year.term_filter'


  properties:
    id:
      attributes:
        identifier: true
        type: integer




App\Entity\Character:
  shortName: 'Characters'                   # optional
  description: 'The characters acting the play'
  attributes:                          # optional
    pagination_items_per_page: 30   # optional
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']


#App\Entity\Work:
#  shortName: 'Plays'                   # optional
#  description: 'aka Works' # optional
